---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rajahema/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp login.php $DEPLOYPATH
    - /bin/cp register.php $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
